// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAzLReVxML5BBk34JmtkBn2vJNgwmsgw',
    appId: '1:930383544572:web:516cc01b647e2a7c789779',
    messagingSenderId: '930383544572',
    projectId: 'linea-de-profundizacion-4e41a',
    authDomain: 'linea-de-profundizacion-4e41a.firebaseapp.com',
    storageBucket: 'linea-de-profundizacion-4e41a.appspot.com',
    measurementId: 'G-0WEPFV6NMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcL_nkyb04m_veFLkkvx5eWZ2F4_NIa4M',
    appId: '1:930383544572:android:8b7443d3828d02c9789779',
    messagingSenderId: '930383544572',
    projectId: 'linea-de-profundizacion-4e41a',
    storageBucket: 'linea-de-profundizacion-4e41a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0e_veAsfCNJVJsVhlmJYEGI9MecDmDyc',
    appId: '1:930383544572:ios:9faf0e9d394d4c4a789779',
    messagingSenderId: '930383544572',
    projectId: 'linea-de-profundizacion-4e41a',
    storageBucket: 'linea-de-profundizacion-4e41a.appspot.com',
    iosClientId: '930383544572-5bggqo85baq9kvbadiv62f2sh1nh39q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lprofundizacionll',
  );
}
